modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="narkoti"
version="1.0.0"
displayName="narkoti"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Like354"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.narkoti]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.narkoti]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.narkoti]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

